### PR TITLE
Get trace from context record.

### LINKED ISSUE #87: MonologHandler using its own debug backtrace, losing exception context
When the exception is being written via Monolog, the `$record` contains `context` parameter with the whole exception and the stack trace of the exception.

`MonologHandler` ignores this and uses its own stack trace causing all exceptions having stack trace pointing to `Monolog\Logger` - https://github.com/airbrake/phpbrake/blob/master/src/MonologHandler.php#L33.

If available, `MonologHandler` should try to read trace from `$record['context']['exception']->getTrace()`.

### PR DESCRIPTION
**Pull request by anmic**
Fixes #87.

### CODE REVIEW

File: src/MonologHandler.php [hunk 1]
```diff
@@ -31,6 +31,8 @@ public function __construct(\Airbrake\Notifier $notifier, $level = Logger::ERROR
     protected function write(array $record)
     {
         $trace = array_slice(debug_backtrace(), 3);
+        $record['context']['exception'] = $trace;
```
Comment (vmihailenco) [inline src/MonologHandler.php]: What does this achieve?

File: tests/MonologHandlerTest.php [hunk 2]
```diff
@@ -65,10 +65,33 @@ public function testBacktrace()
...
     {
         $params = $this->notifier->notice['params'];
-        $this->assertEquals([
-            'monolog_context' => [
-                'client_id' => 123,
-            ],
-        ], $params);
+        $this->assertEquals($params["monolog_context"]["client_id"], 123);
+        $this->assertEquals($params["monolog_context"]["exception"][0], [
+            'file' => '/home/amic/gocode/src/github.com/airbrake/phpbrake/tests/Troublemaker.php',
```
Comment (vmihailenco) [inline tests/MonologHandlerTest.php]: Why this is placed here and what does it test?

**Comment by vmihailenco** [comment]
Build does not pass.

Don't change existing tests without a need. What does this fixes?

File: tests/MonologHandlerTest.php [hunk 3]
```diff
@@ -71,4 +72,35 @@ public function testParams()
             ],
         ], $params);
     }
+
+    public function testAddError()
+    {
+        $this->log->addError('charge failed', [
+            'client_id' => 123, 'exception'=> new Exception(),
```
Comment (vmihailenco) [inline tests/MonologHandlerTest.php]: Split into 2 lines. Use Troublemaker to create an exception

File: tests/MonologHandlerTest.php [hunk 4]
```diff
@@ -71,4 +72,45 @@ public function testParams()
             ],
         ], $params);
     }
+
+    public function testAddError()
```
Comment (vmihailenco) [inline tests/MonologHandlerTest.php]: add proper test name

File: tests/MonologHandlerTest.php [hunk 5]
```diff
@@ -3,6 +3,7 @@
 namespace Airbrake\Tests;
 
 use PHPUnit_Framework_TestCase;
+use Exception;
```
Comment (vmihailenco) [inline tests/MonologHandlerTest.php]: remove

File: tests/MonologHandlerTest.php [hunk 6]
```diff
@@ -13,10 +14,10 @@ public function setUp()
             'projectKey' => 'api_key',
         ]);
 
-        $log = new \Monolog\Logger('billing');
-        $log->pushHandler(new \Airbrake\MonologHandler($this->notifier));
+        $this->log = new \Monolog\Logger('billing');
+        $this->log->pushHandler(new \Airbrake\MonologHandler($this->notifier));
 
-        Troublemaker::logAddError($log);
+        Troublemaker::logAddError($this->log);
```
Comment (vmihailenco) [inline tests/MonologHandlerTest.php]: Move this to appropriate test

File: tests/TroublemakerTest.php [hunk 7]
```diff
@@ -0,0 +1,60 @@
+<?php
+
+namespace Airbrake\Tests;
+
+use PHPUnit_Framework_TestCase;
+
+class TroublemakerTest extends PHPUnit_Framework_TestCase
```
Comment (vmihailenco) [inline tests/TroublemakerTest.php]: This is a test for monolog - it should be in appropriate file
